# Autogenerated from euler.yaml. Do not edit.

{
  description = "beam-mysql";
  inputs = {
    # Laziness of nix allows us to be lazy here and avoid resolving deps
    # The downside is that most of this .follows are redundant
    euler-build.inputs.beam.follows = "beam";
    beam.inputs.euler-build.follows = "euler-build";
  };

  outputs = flakeInputs@{ self, euler-build, ... }:
    euler-build.mkEulerFlake {
      overlayPath = ./nix/overlay.nix;
      extraOverlayPaths = [
        
      ];
      mkConfig = { nixpkgs }: {
        flakeName = "beam-mysql";
        defaultPackageName = "beam-mysql";
        exportPackages = [
          "beam-mysql"
        ];
        shellTools = with nixpkgs; [
          mysql57
          zlib
        ];
        # shellAttrs = {
        # };
      };
      inputs = flakeInputs;
    };
}
